name: Gradle CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: List build/libs directory
      run: ls -l build/libs
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/libs/

  deploy:
      needs: build
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: Setup SSH key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > deploy_key
          chmod 600 deploy_key
      - name: Check workspace
        run: |
          pwd
          ls -l build/libs/
      - name: Deploy to Server
        run: |
          scp -i deploy_key build/libs/discord-bot-1.0-SNAPSHOT.jar root@${{ secrets.SERVER_IP }}:/root/discordBot
          ssh -i deploy_key root@${{ secrets.SERVER_IP }} "systemctl restart discord-bot"
