name: Gradle CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to Server
      run: |
        echo "$DEPLOY_KEY" | tr -d '\r' > deploy_key
        chmod 600 deploy_key
        ssh-keyscan -H 95.214.11.223 >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add deploy_key
        scp build/libs/discord-bot.jar root@95.214.11.223:/root/discordBot
        ssh root@95.214.11.223 "systemctl restart myapp"
  env:
    DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}

      env:
        DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
