name: Gradle CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      run: ./gradlew build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to Server
      run: |
        scp build/libs/discord-bot.jar root@95.214.11.223:/root/discordBot
        ssh root@95.214.11.223 "systemctl restart discord-bot"
      env:
        DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
